### PR TITLE
Adding go.mod and go.sum files to resolve build issues.

### PR DESCRIPTION
**Pull request by nagarwal03**

### CODE REVIEW

**Review by kwangsuk — APPROVED** [review]

**Comment by nagarwal03** [comment]
@anand-kumar-subramanian Please merge this PR.

**Comment by nagarwal03** [comment]
@saiarcot895 Please merge this PR since sonic-mgmt-common submodule has changes that will need the sonic-mgmt-framework and sonic-gnmi to be in sync.

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
